[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gcd = "2.2.0"
ibig = "0.3.6"
itertools = "0.10.5"
nom = "7.1.1"
regex = "1.7.0"
